=== SMoiseenko/Learning/LearningXML/src/main/resources/data/my_first_xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://myXML.com"
  xmlns:tns="http://myXML.com"
  elementFormDefault="qualified">
  <element name="abonents">
    <complexType>
      <sequence>
        <element name="abonent" maxOccurs="unbounded" minOccurs="0" type="tns:Abonent"/>
      </sequence>
    </complexType>
  </element>
  <complexType name="Abonent">
    <sequence>
      <element type="string" name="id"/>
      <element type="string" name="first_name"/>
      <element type="string" name="last_name"/>
      <element type="string" name="email"/>
      <element type="string" name="gender"/>
      <element type="string" name="ip_address"/>
    </sequence>
  </complexType>
</schema>

=== SMoiseenko/Learning/LearningXML/src/test/resources/data/my_first_xml.xml
<?xml version='1.0' encoding='UTF-8'?>
<abonents xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="my_first_xml.xsd">
  <abonent>
    <id>1</id>
    <first_name>Isadore</first_name>
    <last_name>Mation</last_name>
    <email>imation0@soundcloud.com</email>
    <gender>Male</gender>
    <ip_address>124.197.150.248</ip_address>
  </abonent>
</abonents>
